#!/usr/bin/env python3
"""
Generate espresso-cup + steam-wisp icons for GaggiMate's brew "stabilizing" state.

Output: SquareLine-Studio-compatible C files (LVGL 8.3, LV_IMG_CF_TRUE_COLOR_ALPHA).
With LV_COLOR_DEPTH=16 and LV_COLOR_16_SWAP=0, each pixel is 3 bytes:
    [RGB565 low byte, RGB565 high byte, alpha]
Icons are stored as solid black (0x0000) so the existing theme RECOLOR turns them
NiceWhite, exactly like the other UI icons. Only the alpha channel carries the shape.

Dependency-free: shapes are drawn with signed-distance functions and 3x3 supersampling.
"""

import math

SS = 3  # supersampling factor per axis


def clamp(v, lo, hi):
    return lo if v < lo else hi if v > hi else v


def smooth_cover(dist):
    """Anti-aliased inside coverage from a signed distance (negative = inside)."""
    return clamp(0.5 - dist, 0.0, 1.0)


# ---------- SDF primitives (all in icon-local pixel coords) ----------

def sd_circle(px, py, cx, cy, r):
    return math.hypot(px - cx, py - cy) - r


def sd_ellipse_solid(px, py, cx, cy, rx, ry):
    """Cheap ellipse SDF (good enough for AA at this size)."""
    nx = (px - cx) / rx
    ny = (py - cy) / ry
    d = math.hypot(nx, ny) - 1.0
    # scale back to pixel units roughly
    return d * min(rx, ry)


def sd_segment(px, py, ax, ay, bx, by):
    pax, pay = px - ax, py - ay
    bax, bay = bx - ax, by - ay
    denom = bax * bax + bay * bay
    h = 0.0 if denom == 0 else clamp((pax * bax + pay * bay) / denom, 0.0, 1.0)
    return math.hypot(pax - bax * h, pay - bay * h)


# ---------- Shape coverage functions ----------

def cup_alpha(px, py, W, H):
    """A small demitasse cup with a handle, sitting on a saucer."""
    cover = 0.0

    # Saucer: a flat shallow dish (solid ellipse line)
    d = sd_ellipse_solid(px, py, W / 2.0, H - 2.0, W / 2.0 - 1.0, 2.3)
    cover = max(cover, smooth_cover(d))

    # Cup body: tapered trapezoid with a rounded bottom
    top_y, bot_y = 6.0, H - 5.0
    if top_y - 1.0 <= py <= bot_y + 4.0:
        t = clamp((py - top_y) / (bot_y - top_y), 0.0, 1.0)
        half_w = (W / 2.0 - 9.0) - t * 4.0  # ~14 -> ~10
        # vertical sides
        dx = abs(px - W / 2.0) - half_w
        dy = max(top_y - py, py - bot_y)
        body = max(dx, dy)
        cover = max(cover, smooth_cover(body))
    # rounded bottom cap
    cap = sd_ellipse_solid(px, py, W / 2.0, bot_y, W / 2.0 - 13.0, 4.0)
    if py >= bot_y - 4.0:
        cover = max(cover, smooth_cover(cap))

    # Handle: an annulus (ring) on the right side
    ring_cx, ring_cy = W - 8.0, 15.0
    outer = sd_circle(px, py, ring_cx, ring_cy, 6.0)
    inner = sd_circle(px, py, ring_cx, ring_cy, 3.0)
    if px >= W / 2.0 + 6.0:  # keep only the right portion so it reads as a handle
        ring = max(outer, -inner)  # annulus
        cover = max(cover, smooth_cover(ring))

    return clamp(cover, 0.0, 1.0)


def wisp_alpha(px, py, W, H):
    """A single wavy steam curl, thicker/brighter at the bottom, wispy at the top."""
    # Build a polyline along a sine wave from bottom to top.
    N = 96
    best = 1e9
    best_t = 0.0
    pts = []
    for i in range(N + 1):
        t = i / N                      # 0 at bottom, 1 at top
        y = H - t * H
        x = W / 2.0 + 3.0 * math.sin(2.0 * math.pi * t + 0.35)
        pts.append((x, y, t))
    for i in range(N):
        ax, ay, ta = pts[i]
        bx, by, tb = pts[i + 1]
        d = sd_segment(px, py, ax, ay, bx, by)
        if d < best:
            best = d
            best_t = (ta + tb) * 0.5
    # stroke half-width tapers from ~1.3 (bottom) to ~0.7 (top)
    half = 1.3 - 0.6 * best_t
    cover = smooth_cover(best - half)
    # extra wispy fade towards the top
    taper = 1.0 - 0.45 * best_t
    return clamp(cover * taper, 0.0, 1.0)


# ---------- Rasterize + emit ----------

def rasterize(W, H, fn):
    px_bytes = bytearray()
    for y in range(H):
        for x in range(W):
            acc = 0.0
            for sy in range(SS):
                for sx in range(SS):
                    fx = x + (sx + 0.5) / SS
                    fy = y + (sy + 0.5) / SS
                    acc += fn(fx, fy, W, H)
            a = int(round(255.0 * acc / (SS * SS)))
            a = clamp(a, 0, 255)
            px_bytes.append(0x00)  # RGB565 low  (black)
            px_bytes.append(0x00)  # RGB565 high (black)
            px_bytes.append(a)     # alpha
    return bytes(px_bytes)


def emit_c(path, name, W, H, data, src_comment):
    lines = []
    lines.append("// This file was generated by GaggiMate (gen_steam_icons.py)")
    lines.append("// Animated brew 'stabilizing' steam indicator asset.")
    lines.append("// LVGL version: 8.3.11  /  LV_IMG_CF_TRUE_COLOR_ALPHA (16bpp, 3 bytes/px)")
    lines.append("")
    lines.append('#include "../ui.h"')
    lines.append("")
    lines.append("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    lines.append("#define LV_ATTRIBUTE_MEM_ALIGN")
    lines.append("#endif")
    lines.append("")
    lines.append(f"// IMAGE DATA: {src_comment}")
    lines.append(f"const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_data[] = {{")
    per = 12 * 3  # 12 pixels per text row
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02X}")
        if (i + 1) % per == 0:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_img_dsc_t {name} = {{")
    lines.append("    .header.always_zero = 0,")
    lines.append(f"    .header.w = {W},")
    lines.append(f"    .header.h = {H},")
    lines.append(f"    .data_size = sizeof({name}_data),")
    lines.append("    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,")
    lines.append(f"    .data = {name}_data,")
    lines.append("};")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return len(data)


def ascii_preview(W, H, fn, title):
    ramp = " .:-=+*#%@"
    print(f"--- {title} ({W}x{H}) ---")
    for y in range(H):
        line = []
        for x in range(W):
            acc = 0.0
            for sy in range(SS):
                for sx in range(SS):
                    acc += fn(x + (sx + 0.5) / SS, y + (sy + 0.5) / SS, W, H)
            a = acc / (SS * SS)
            line.append(ramp[clamp(int(a * (len(ramp) - 1)), 0, len(ramp) - 1)])
        print("".join(line))
    print()


if __name__ == "__main__":
    import sys

    out_dir = sys.argv[1] if len(sys.argv) > 1 else "."

    CUP_W, CUP_H = 46, 32
    WISP_W, WISP_H = 14, 28

    ascii_preview(CUP_W, CUP_H, cup_alpha, "espresso cup")
    ascii_preview(WISP_W, WISP_H, wisp_alpha, "steam wisp")

    cup_data = rasterize(CUP_W, CUP_H, cup_alpha)
    wisp_data = rasterize(WISP_W, WISP_H, wisp_alpha)

    n1 = emit_c(f"{out_dir}/ui_img_steamcup.c", "ui_img_steamcup",
                CUP_W, CUP_H, cup_data, "generated/espresso-cup-46x32 (steam indicator)")
    n2 = emit_c(f"{out_dir}/ui_img_steamwisp.c", "ui_img_steamwisp",
                WISP_W, WISP_H, wisp_data, "generated/steam-wisp-14x28 (steam indicator)")

    assert n1 == CUP_W * CUP_H * 3, (n1, CUP_W * CUP_H * 3)
    assert n2 == WISP_W * WISP_H * 3, (n2, WISP_W * WISP_H * 3)
    print(f"ui_img_steamcup.c  bytes={n1} (expect {CUP_W*CUP_H*3})")
    print(f"ui_img_steamwisp.c bytes={n2} (expect {WISP_W*WISP_H*3})")
