#!/usr/bin/env python3
"""
png_gif_to_lvgl.py — Convert PNG or GIF to LVGL 8.x C image assets
                      for GaggiMate (LV_COLOR_DEPTH=16, TRUE_COLOR_ALPHA)

Output format: 3 bytes/pixel → [RGB565_lo, RGB565_hi, alpha8]

Usage:
    python3 scripts/png_gif_to_lvgl.py <input.png|input.gif> [options]

Options:
    --name NAME       C symbol name  (default: derived from filename)
    --size WxH        Resize to WxH  (default: 40x40)
    --out DIR         Output directory (default: src/display/ui/default/lvgl/images)
    --white           Convert to white + alpha (recolorable via lv_obj_set_style_img_recolor)
    --bg R,G,B        Background color to treat as transparent for PNGs without alpha (default: none)

GIF input:  produces one .c file per frame → ui_img_NAME_f0.c, ui_img_NAME_f1.c ...
            and prints the LV_IMG_DECLARE lines and the lv_img_dsc_t* array for lv_animimg.
PNG input:  produces a single ui_img_NAME.c file.

Examples:
    # Convert a 40x40 PNG to a recolorable white icon
    python3 scripts/png_gif_to_lvgl.py flame.png --white

    # Convert a GIF animation to frame files at 40x40
    python3 scripts/png_gif_to_lvgl.py steam.gif --size 40x40 --name steamwisp

    # Convert a PNG, keep original colors, output to custom dir
    python3 scripts/png_gif_to_lvgl.py icon.png --name myicon --out /tmp/icons
"""

import argparse
import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow not found. Run: pip install Pillow --break-system-packages")


DEFAULT_OUT = "src/display/ui/default/lvgl/images"


def to_rgb565_alpha(img: Image.Image, white_mode: bool) -> bytes:
    """Convert an RGBA PIL image to LVGL TRUE_COLOR_ALPHA bytes (3 bytes/pixel)."""
    img = img.convert("RGBA")
    out = bytearray()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = img.getpixel((x, y))
            if white_mode:
                # Store as white; alpha encodes the original luminance × original alpha
                lum = int(0.299 * r + 0.587 * g + 0.114 * b)
                a = (lum * a) // 255
                r, g, b = 255, 255, 255
            val = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            out += bytes([val & 0xFF, (val >> 8) & 0xFF, a])
    return bytes(out)


def make_c_file(name: str, w: int, h: int, data: bytes) -> str:
    """Render a .c file string matching the project's SquareLine format."""
    hex_rows = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_rows.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    hex_body = "\n".join(hex_rows)

    return f"""\
// Generated by scripts/png_gif_to_lvgl.py
// Add to ui.h: LV_IMG_DECLARE({name});

#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_data[] = {{
{hex_body}
}};

const lv_img_dsc_t {name} = {{
    .header.always_zero = 0,
    .header.w           = {w},
    .header.h           = {h},
    .data_size          = sizeof({name}_data),
    .header.cf          = LV_IMG_CF_TRUE_COLOR_ALPHA,
    .data               = {name}_data,
}};
"""


def slugify(s: str) -> str:
    return s.replace("-", "_").replace(" ", "_").lower()


def convert(args):
    src = Path(args.input)
    if not src.exists():
        sys.exit(f"File not found: {src}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Parse size
    try:
        w, h = (int(x) for x in args.size.lower().split("x"))
    except Exception:
        sys.exit("--size must be WxH, e.g. 40x40")

    # Derive symbol name
    base_name = args.name if args.name else slugify(src.stem)
    sym_prefix = f"ui_img_{base_name}"

    img = Image.open(src)
    is_gif = getattr(img, "is_animated", False) or src.suffix.lower() == ".gif"

    frames = []
    if is_gif:
        try:
            i = 0
            while True:
                img.seek(i)
                frames.append(img.copy().convert("RGBA").resize((w, h), Image.LANCZOS))
                i += 1
        except EOFError:
            pass
    else:
        # Handle white background removal if requested
        frame = img.convert("RGBA").resize((w, h), Image.LANCZOS)
        if args.bg:
            try:
                br, bg, bb = (int(x) for x in args.bg.split(","))
                pixels = frame.load()
                for py in range(h):
                    for px in range(w):
                        r, g, b, a = pixels[px, py]
                        if abs(r - br) < 20 and abs(g - bg) < 20 and abs(b - bb) < 20:
                            pixels[px, py] = (r, g, b, 0)
            except Exception as e:
                print(f"Warning: --bg parsing failed: {e}")
        frames.append(frame)

    frame_syms = []
    for i, frame in enumerate(frames):
        sym = f"{sym_prefix}_f{i}" if len(frames) > 1 else sym_prefix
        data = to_rgb565_alpha(frame, args.white)
        c_src = make_c_file(sym, w, h, data)
        out_path = out_dir / f"{sym}.c"
        out_path.write_text(c_src)
        frame_syms.append(sym)
        print(f"  Wrote {out_path}  ({w}×{h}, {len(data)} bytes)")

    # Print ui.h declarations
    print("\n--- Add to ui.h ---")
    for sym in frame_syms:
        print(f"LV_IMG_DECLARE({sym});")

    # For multi-frame GIF: print lv_animimg frame array
    if len(frames) > 1:
        arr = ", ".join(f"(const void*)&{s}" for s in frame_syms)
        print(f"\n--- lv_animimg frame array (in DefaultUI.cpp) ---")
        print(f"static const lv_img_dsc_t* {base_name}_frames[] = {{ {arr} }};")
        print(f"lv_animimg_set_src(my_animimg, (lv_img_dsc_t**)  {base_name}_frames, {len(frames)});")
        print(f"lv_animimg_set_duration(my_animimg, <total_ms>);")
        print(f"lv_animimg_set_repeat_count(my_animimg, LV_ANIM_REPEAT_INFINITE);")
        print(f"lv_animimg_start(my_animimg);")

    print(f"\nDone — {len(frames)} frame(s) written to {out_dir}/")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input", help="Input PNG or GIF file")
    p.add_argument("--name",  default="", help="C symbol base name (default: filename stem)")
    p.add_argument("--size",  default="40x40", help="Output size WxH (default: 40x40)")
    p.add_argument("--out",   default=DEFAULT_OUT, help="Output directory")
    p.add_argument("--white", action="store_true", help="Convert to white+alpha (theme-recolorable)")
    p.add_argument("--bg",    default="", help="Background color to make transparent: R,G,B (e.g. 255,255,255)")
    convert(p.parse_args())


if __name__ == "__main__":
    main()
